os: osx
language: emacs-lisp
sudo: false

install:
  - cd ~
  - git clone https://github.com/casouri/lunarymacs.git .emacs.d --recurse-submodules
  - cd .emacs.d
  - git clone https://github.com/casouri/lunarymacs-stars.git star
  - brew tap d12frosted/emacs-plus
  - brew install emacs-plus
  - brew install make
  - PATH="/usr/local/opt/make/libexec/gnubin:${PATH}"
  - export PATH
  - cp init.test.el init.el

script:
  - make
  - make test

