;; https://www.emacswiki.org/emacs/iTerm2#toc11
;; TERMINAL MAPPINGS TO SUPPORT ITERM2 FOR MAC
(progn
  (let ((map (if (boundp 'input-decode-map)
                 input-decode-map
               function-key-map)))
    (define-key map "\e[1;P9"  (kbd "s-a"))
    (define-key map "\e[1;P10" (kbd "s-b"))
    (define-key map "\e[1;P11" (kbd "s-c"))
    (define-key map "\e[1;P12" (kbd "s-d"))
    (define-key map "\e[1;P13" (kbd "s-e"))
    (define-key map "\e[1;P14" (kbd "s-f"))
    (define-key map "\e[1;P15" (kbd "s-g"))
    (define-key map "\e[1;P16" (kbd "s-h"))
    (define-key map "\e[1;P17" (kbd "s-i"))
    (define-key map "\e[1;P18" (kbd "s-j"))
    (define-key map "\e[1;P19" (kbd "s-k"))
    (define-key map "\e[1;P20" (kbd "s-l"))
    (define-key map "\e[1;P21" (kbd "s-m"))
    (define-key map "\e[1;P22" (kbd "s-n"))
    (define-key map "\e[1;P23" (kbd "s-o"))
    (define-key map "\e[1;P24" (kbd "s-p"))
    (define-key map "\e[1;P25" (kbd "s-q"))
    (define-key map "\e[1;P26" (kbd "s-r"))
    (define-key map "\e[1;P27" (kbd "s-s"))
    (define-key map "\e[1;P28" (kbd "s-t"))
    (define-key map "\e[1;P29" (kbd "s-u"))
    (define-key map "\e[1;P30" (kbd "s-v"))
    (define-key map "\e[1;P31" (kbd "s-w"))
    (define-key map "\e[1;P32" (kbd "s-x"))
    (define-key map "\e[1;P33" (kbd "s-y"))
    (define-key map "\e[1;P34" (kbd "s-z"))
    (define-key map "\e[1;P35" (kbd "s-0"))
    (define-key map "\e[1;P36" (kbd "s-1"))
    (define-key map "\e[1;P37" (kbd "s-2"))
    (define-key map "\e[1;P38" (kbd "s-3"))
    (define-key map "\e[1;P39" (kbd "s-4"))
    (define-key map "\e[1;P40" (kbd "s-5"))
    (define-key map "\e[1;P41" (kbd "s-6"))
    (define-key map "\e[1;P42" (kbd "s-7"))
    (define-key map "\e[1;P43" (kbd "s-8"))
    (define-key map "\e[1;P44" (kbd "s-9"))
    (define-key map "\e[1;P45" (kbd "s-<f1>"))
    (define-key map "\e[1;P46" (kbd "s-<f2>"))
    (define-key map "\e[1;P47" (kbd "s-<f3>"))
    (define-key map "\e[1;P48" (kbd "s-<f4>"))
    (define-key map "\e[1;P49" (kbd "s-<f5>"))
    (define-key map "\e[1;P50" (kbd "s-<f6>"))
    (define-key map "\e[1;P51" (kbd "s-<f7>"))
    (define-key map "\e[1;P52" (kbd "s-<f8>"))
    (define-key map "\e[1;P53" (kbd "s-<f9>"))
    (define-key map "\e[1;P54" (kbd "s-<f10>"))
    (define-key map "\e[1;P55" (kbd "s-<f11>"))
    (define-key map "\e[1;P56" (kbd "s-<f12>"))
    ))
