(require 'theme-util)

(deftheme light
  "Light theme.")

(theme-util-deffaces
 (highlight-fg-only-2 "Base face.")
 (highlight-fg-only-1 "Base face.")
 (red-bg-hl "Base face.")
 (red-bg "Base face.")
 (yellow-bg-hl "Base face.")
 (yellow-bg "Base face.")
 (green-bg-hl "Base face.")
 (green-bg "Base face.")
 (comp-scroll-bar "Base face.")
 (comp-mouse "Base face.")
 (selection-common "Base face.")
 (comp-common "Base face.")
 (current-selection "Base face.")
 (magit-heading-selection "Base face.")
 (magit-heading-highlight "Base face."))

(theme-util-set-faces 'light
  (cl-flet ((darken #'theme-util-darken)
            (brighten #'theme-util-brighten)
            (overlay #'theme-util-color-overlay))
    (let* ((bg        "#fefefc")
           ;; lighter than region
           (bg-alt    (darken bg 0.05))
           (fg        "#2b3239")
           (fg-weak   "#9ca0a4")
           (fg-strong "#0e0e0e")
           (blue1     "#a0bcf8")
           (blue2     "#4078f2")
           (green     "#50a14f")
           (orange    "#da8548")
           (red       "#e45649")
           (yellow    "#986801")
           (violet1   "#b751b6")
           (violet2   "#a626a4"))
      `(;; builtin faces
        (default     (nil ,fg ,bg))
        (region      (nil nil ,(overlay bg blue1 0.2)))
        (highlight   (nil "white" ,blue2))
        (cursor      (nil "white" "black"))
        (link        (nil ,blue2 nil t))
        (match       (nil ,green nil nil bold))
        (error       (nil ,red))
        (warning     (nil ,yellow))
        (sucess      (nil ,green))
        (tooltip     (nil nil ,(darken bg 0.03)))
        (fringe      (default))
        (trailing-whitespace (nil nil ,red))
        (shadow      (nil nil ,bg-alt))
        (variable-pitch () (:family "Source Serif Pro" :height 150))
        (fixed-pitch () (:family "SF Mono" :height 130))
        (vertical-border                     (nil nil "black"))
        (lazy-highlight                      (nil "black" nil nil bold))
        (highlight-fg-only-1                 (nil ,blue2))
        (highlight-fg-only-2                 (nil ,violet1))
        (minibuffer-prompt                   (highlight-fg-only-1))
        (secondary-selection                 (nil nil ,(overlay bg blue1 0.3)))

        (font-lock-builtin-face              (nil ,violet2))
        (font-lock-comment-face              (nil ,fg-weak))
        (font-lock-comment-delimiter-face    (font-lock-comment-face))
        (font-lock-doc-face                  (font-lock-comment-face))
        (font-lock-constant-face             (nil ,violet1))
        (font-lock-function-name-face        (nil ,violet2))
        (font-lock-keyword-face              (nil ,red))
        (font-lock-string-face               (nil ,green))
        (font-lock-type-face                 (nil ,yellow))
        (font-lock-variable-name-face        (nil ,violet2))
        (font-lock-warning-face              (warning))
        (font-lock-negation-char-face        (nil ,blue2))
        (font-lock-preprocessor-face         (nil ,blue2))
        (font-lock-preprocessor-char-face    (nil ,blue2))
        (font-lock-regexp-grouping-backslash (nil ,blue2))
        (font-lock-regexp-grouping-construct (nil ,blue2))

        (mode-line                           (nil nil ,(darken bg 0.07))
                                             (:font ,(font-spec :family "SF Pro Text" :size 13.0 :weight 'light)
                                                    :box (:line-width 2 :color ,(darken bg 0.07))))
        (mode-line-inactive                  (mode-line nil ,(darken bg 0.04) nil nil nil)
                                             (:box (:line-width 2 :color ,(darken bg 0.04))))

        ;; completion
        (current-selection                   (nil ,bg ,blue2))
        (comp-common                         (nil ,violet1))
        (selection-common                    (current-selection ,bg))
        (comp-mouse                          (nil ,bg ,violet2))
        
        (custom-face-tag (nil ,blue2))

        (isearch (bold))
        (isearch-fail (error))
        (show-paren-match (bold))

        ;; package faces

        
        (company-tooltip                     (tooltip))
        (company-tooltip-annotation          (company-tooltip))
        (company-tooltip-common              ((comp-common company-tooltip)))
        (company-tooltip-common-selection    ((selection-common company-tooltip)))
        (company-tooltip-mouse               ((comp-mouse company-tooltip)))
        (company-tooltip-selection           ((current-selection company-tooltip)))
        (company-scrollbar-bg                (company-tooltip))
        (company-scrollbar-fg                (company-tooltip nil ,blue2))
        (company-preview                     (highlight-fg-only-1))
        (company-preview-common              (company-preview))
        (company-preview-search              (company-preview))
        
        (ivy-current-match                   (current-selection))
        (ivy-minibuffer-match-face-1         (nil ,blue2))
        ;; (ivy-minibuffer-match-face-2      (nil ,green))
        ;; (ivy-minibuffer-match-face-3      (nil ,yellow))
        ;; (ivy-minibuffer-match-face-4      (nil ,violet2))

        (magit-heading-highlight (nil ,bg ,(overlay bg violet2 0.8)))
        (magit-heading-selection (nil ,bg ,(overlay bg orange 0.8)))
        (magit-bisect-bad (nil ,red))
        (magit-bisect-good (nil ,green))
        (magit-bisect-skip (nil ,orange))
        (magit-blame-date (nil ,blue2))
        (magit-blame-heading (magit-heading ,orange))
        (magit-branch-current (nil ,blue2))
        (magit-branch-local (nil ,blue2))
        (magit-branch-remote (nil ,green))
        (magit-cherry-equivalent (nil ,violet1))
        (magit-cherry-unmatched (nil ,blue2))
        (magit-tag (nil ,yellow))
        (magit-filename (nil ,violet1))
        
        (magit-diff-added (nil ,green ,(overlay bg green 0.1)))
        (magit-diff-added-highlight (nil ,green ,(overlay bg green 0.2)))

        (magit-diff-removed (nil ,red ,(overlay bg red 0.1)))
        (magit-diff-removed-highlight (nil ,red ,(overlay bg red 0.2)))

        (magit-diff-base (nil ,orange ,(overlay bg orange 0.1)))
        (magit-diff-base-highlight (nil ,orange ,(overlay bg orange 0.2)))

        (magit-diff-context (default))
        (magit-diff-context-highlight (nil ,fg ,bg-alt))
        
        (magit-diff-file-heading (default))
        (magit-diff-file-heading-highlight (magit-heading-highlight))
        (magit-diff-file-heading-selection (magit-heading-selection))
        
        (magit-diff-hunk-heading (nil ,bg ,(overlay bg violet2 0.2)))
        (magit-diff-hunk-heading-highlight (magit-heading-highlight))
        (magit-diff-hunk-heading-selection (magit-heading-selection))
        ;; selected hunk region
        (magit-diff-hunk-region (italic))
        ;; this also determines the hunk region boundary
        (magit-diff-lines-heading (nil ,bg ,red))
        
        (magit-section-heading (nil ,blue2))
        (magit-section-highlight (magit-heading-highlight))
        (magit-section-heading-selection (magit-heading-selection))

        
        (magit-diffstat-added (nil ,green))
        (magit-diffstat-removed (nil ,red))
        (magit-dimmed (nil ,fg-weak))
        (magit-hash   (nil ,fg-weak))
        (magit-header-line (nil nil ,blue2 nil bold nil (:box (:line-width 3 :color ,blue2))))
        (magit-log-author (nil ,orange))
        (magit-log-date (nil ,blue2))
        (magit-log-graph (nil ,fg-weak))
        (magit-process-ng (error))
        (magit-process-ok (success))
        (magit-reflog-amend (nil ,violet2))
        (magit-reflog-checkout (nil ,blue2))
        (magit-reflog-cherry-pick (nil ,green))
        (magit-reflog-commit (nil ,green))
        (magit-reflog-merge (nil ,green))
        (magit-reflog-other (nil ,blue2))
        (magit-reflog-rebase (nil ,violet2))
        (magit-reflog-remote (nil ,blue2))
        (magit-reflog-reset (error))
        (magit-refname (nil ,fg-weak))
        (magit-sequence-drop (nil ,red))
        (magit-sequence-head (nil ,blue2))
        (magit-sequence-part (nil ,orange))
        (magit-sequence-stop (nil ,green))
        (magit-signature-bad (error))
        (magit-signature-error (error))
        (magit-signature-expired (nil ,orange))
        (magit-signature-good (success))
        (magit-signature-revoked (nil ,orange))
        (magit-signature-untrusted (nil ,orange))
        (magit-section-secondary-heading (nil ,violet1))

        (rainbow-delimiters-depth-1-face (nil ,blue2))
        (rainbow-delimiters-depth-2-face (nil ,violet2))
        (rainbow-delimiters-depth-3-face (nil ,green))
        (rainbow-delimiters-depth-4-face (nil ,orange))
        (rainbow-delimiters-depth-5-face (nil ,violet1))
        (rainbow-delimiters-depth-6-face (nil ,yellow))
        (rainbow-delimiters-depth-7-face (nil ,blue2))
        (rainbow-delimiters-unmatched-face (nil ,red))
        (rainbow-delimiters-mismatched-face (rainbow-delimiters-unmatched-face))

        (smerge-lower (magit-diff-added))
        (smerge-upper (magit-diff-removed))
        (smerge-base  (magit-diff-base))
        (smerge-markers (nil nil nil nil bold))

        (which-key-key-face                   (nil ,green))
        (which-key-group-description-face     (nil ,violet1))
        (which-key-command-description-face   (nil ,blue2))
        (which-key-local-map-description-face (nil ,violet2))

        (hl-paren-face (nil ,(darken red 0.1) nil nil bold))

        (outline-1 (info-title-2))
        (outline-2 (info-title-3))
        (outline-3 (info-title-4))
        (outline-4 (outline-3))
        (outline-5 (outline-3))
        (outline-6 (outline-3))
        (outline-7 (outline-3))
        (outline-8 (outline-3))

        (org-document-title (info-title-1))
        (org-meta-line (font-lock-comment-face nil nil nil nil italic))
        (org-document-info (org-meta-line))
        (org-document-info-keyword (org-meta-line))

        (org-verbatim (fixed-pitch))
        (org-code (org-verbatim))
        (org-block ((org-verbatim org-meta-line) nil ,bg-alt) (:extend t))
        (org-block-begin-line (org-block))
        (org-block-end-line (org-block))

        (org-table (fixed-pitch))
        (org-todo (highlight-fg-only-1))
        (org-time-grid (nil ,yellow))
        (org-upcoming-deadline (nil ,red))
        
        (helpful-heading (info-title-3))

        (ghelp-entry-title (info-title-2))

        (diff-hl-change (nil ,orange ,(overlay bg orange 0.1)))))))

(provide-theme 'light)

