#+TITLE: Customization


Most of the settings should be in =config.el= in stars.

However, for some settings that you want to change by your mood,
you can expose APIs and set them in =init.el=.

In =init.el=:

- Before loading =package.el= and =config.el=.

  Set them in init.el.
- After loading =package.e= and =config.el= and all package loaded

  Use =customize= macro.

For example in =init.el=:
#+BEGIN_SRC lisp
(customize| 
 (setq moon-maximize-on-startup t)
 (setq moon-normal-state-cursor-color (lambda () lunary-white))
 (setq moon-insert-state-cursor-color (lambda () spacemacs-yellow))
)
#+END_SRC

It sets cursor color of normal state to white, 
that of insert state to yellow. 
There is also =doom-blue= and a bunch of colors that you can use.

These colors are all in =moon-color-book=. Check them out.

* Customize theme

You need to load your own theme in star.

An example is in my star [[https://github.com/casouri/lunarymacs/blob/028d86d1d4550c10f47129b3e221b5b809fba86b/star/basic/ui/config.el#L26][ui]]

There are some helpers for theme,font and cursor color
explained in next page.

An example configuration:

#+BEGIN_SRC lisp
;; used for SPC t t "toggle theme"
(setq moon-toggle-theme-list '(spacemacs-dark spacemacs-light))
;; set font
(add-to-list 'moon-magic-font-book '("SF Mono" . (moon-set-font| :family "SF Mono" :weight 'light :size 14)))

#+END_SRC



-----

#+HTML:<div align=left>
[[https://github.com/casouri/lunarymacs/wiki/getting-started][<<< Previous page ( ﾟДﾟ)ﾉ <<<]]
#+HTML:</div>

#+HTML:<div align=right>
[[https://github.com/casouri/lunarymacs/wiki/helper][>>> Next page (￣▽￣)ノ >>>]]
#+HTML:</div>
