#+TITLE: Helper functions, macros, and commands

You have seen =moon|=, =use-package|=, 
=package|=, =pre-init|=,
=after-load|= and =post-config|= macro.

Besides them, there are some other helpers that can aid you
when configuring Emacs.

Use C-h f to find documentation about them.

* Defined in core

These helpers are defined in core so they are always avaliable.
Other helpers may be in a star so you have to enable that star
to use them.

** Commands

*** moon/switch-theme
switch theme to the next one in =moon-toggle-theme-list=.
Default value of =moon-toggle-theme-list= is 
'(spacemacs-dark spacemacs-light)

*** moon/load-font 
Prompt to let you select a font and load it.

Fonts are specified in =moon-magic-font-book=.
Each element is an alist with the form:
(name . (moon-set-font| configuration))
(name . (moon-set-font| :family "family" :weight ’weight))

*** moon/rename-file
*I got this code from Stak Overflow:*
https://stackoverflow.com/questions/384284/how-do-i-rename-an-open-file-in-emacs

rename the current file
** Macros
*** customize|

It is explained in [[https://github.com/casouri/lunarymacs/wiki/customization][customization]] tab.

*** moon-set-font|

Set font. Accepts `font-spec' arguments.

e.g. :family :weight :size etc.

*** change-cursor-on-hook|

Change cursor color to COLOR when HOOK is activated.

COLOR is a function that returns a string that specify a color.
This way to change change cursor color depend on current theme
or something else


*** add-hook-for-once|

Add FUNC to HOOK. And remove FUNC from HOOK at first call of FUNC.
Could be uedful for lazy loading.

*** delay-load|

Add FUNC to `after-change-major-mode-hook' 
and remove FUNC from the hook at first call.

*** load|
Just load a file relative to current file's path.
   

*** async-load|
Make a new thread to require the package

Expand to a expression like:

#+BEGIN_SRC lisp
(make-thread (lambda () (require 'PACKAGE)) NAME)
#+END_SRC

Use example:

#+BEGIN_SRC lisp
(use-package| PACKAGE :init (async-load| PACKAGE))
#+END_SRC

** Functions


-----

#+HTML:<div align=left>
[[https://github.com/casouri/lunarymacs/wiki/customization][<<< Previous page ( ﾟДﾟ)ﾉ <<<]]
#+HTML:</div>

#+HTML:<div align=right>
[[https://github.com/casouri/lunarymacs/wiki/core][>>> Next page (￣▽￣)ノ >>>]]
#+HTML:</div>
